#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include "NGLScene.h"

// forward declare our MainWindow class
namespace Ui {
	class MainWindow;
}

class MainWindow : public QMainWindow
{
Q_OBJECT
public:
	explicit MainWindow(QWidget *parent = 0);
	~MainWindow();

public slots:
	//----------------------------------------------------------------------------------------------------------------------
	/// @brief this is called to set the positions of the light
	//----------------------------------------------------------------------------------------------------------------------
	void setLightPosition();

private:
	//----------------------------------------------------------------------------------------------------------------------
	/// @brief the class generated by our qt .ui file
	//----------------------------------------------------------------------------------------------------------------------
	Ui::MainWindow *m_ui;
	//----------------------------------------------------------------------------------------------------------------------
	/// @brief our OpenGL widget
	//----------------------------------------------------------------------------------------------------------------------
	NGLScene *m_gl;
};

#endif // MAINWINDOW_H
